apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: devacrcluster/.azurecr.io//azure-vote-front
    newTag: 20250115.12.59.18
  - name: devacrcluster/.azurecr.io//azure-vote-back
    newTag: 20250115.13.00.05
resources:
  - manifests.yaml